version: '3.4'
services:
  nuxt:
    container_name: nuxt-docker
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
       - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules
